[connections.postgresql]
dialect = "postgresql"
host = "mdi"
port = "5432"
database = "mdi"
username = "mdi"
password = "1234"
[openai]
key = "sk-..."
[geral]
mdilink="https://moodledataimport1.websiteseguro.com"
jwt="56973d6a8dbf7cd58330565e28f2b24d  -"